name: ProjectKorraMobs
version: 1.0.9
authors: [jedk1, Simplicitee, Dooder07]
main: com.jedk1.projectkorra.mobs.ProjectKorraMobs
depend: [ProjectKorra]
softdepend: [LibsDisguises]

commands:
  projectkorramobs:
    aliases: [pkm, bm, pkmobs, bendingmobs, bendmobs]
    usage: /<command>
    
permissions:
  bendingmobs.admin:
    default: op
    description: Grants access to all commands.
    children:
      bendingmobs.command.spawn: true